export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_TOP_PRODUCTS = "GET_TOP_PRODUCTS";
export const GET_TOP_PRODUCTS_FAILED = "GET_TOP_PRODUCTS_FAILED";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
